#!/usr/bin/env bash
# 4-TCP_and_UDP_ports: Script that displays listening ports (TCP, UDP, UNIX)

echo "Active Internet connections (only servers)"
# -l : Show only listening sockets
# -n : Numeric addresses (optionnel)
# -t : TCP
# -u : UDP
# -p : Show PID/Program name
netstat -lntup

echo
echo "Active UNIX domain sockets (only servers)"
# -l : Show only listening sockets
# -x : UNIX domain sockets
# -p : Show PID/Program name
netstat -lxp
