#!/usr/bin/env bash
# Displays listening ports (TCP, UDP, and UNIX) with PID/Program name.

echo "Active Internet connections (only servers)"
# -l : Show only listening sockets
# -n : Numeric addresses (optionnel)
# -t : TCP
# -u : UDP
# -p : Show PID/Program name
netstat -lntup

echo "Active UNIX domain sockets (only servers)"
# -l : Show only listening sockets
# -x : UNIX domain sockets
# -p : Show PID/Program name
netstat -lxp
